# Site settings
course_name: CIS 5640 Game Design and Development
course_description: "This course is a hands-on introduction to the craft of game design. Students will learn a variety of techniques to ideate, iterate and playtest and analyze games by breaking down the relationships between mechanics, themes and the powerful emotional experiences that games can create. Students will work on a variety of small in-class team-based projects to develop skills that translate directly into future real-world projects."
course_semester: "Spring 2025"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cis-5640-spring-2025.github.io" # the base hostname & protocol for your site

schoolname: "University of Pennsylvania"
schoolurl: "https://upenn.edu"

address: |
    220 South 33rd Street
    107 Towne Building
    Philadelphia, PA

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
